# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
        - 27017:27017
